<?php

use Illuminate\Database\Seeder;

class ReleaseMilestonesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('release_milestones')->delete();

        \DB::table('release_milestones')->insert([
            0 => [
                'id' => 1,
                'release_numbers_id' => 3,
                'release_start_date' => '2020-01-15',
                'release_end_date' => '2020-02-26',
                'baseline_start_date' => null,
                'baseline_end_date' => null,
                'number_of_sprints' => null,
                'content_complete_start_date' => '2020-02-19',
                'content_complete_end_date' => '2020-02-19',
                'regressions_start_date' => '2020-02-19',
                'regressions_end_date' => '2020-02-24',
                'enablement_delivery' => 'Y',
                'enablement_delivery_start_date' => null,
                'enablement_delivery_end_date' => null,
                'localization_review' => 'Y',
                'localization_start_date' => null,
                'localization_end_date' => null,
                'run_security_scan' => 'Y',
                'security_scan_start_date' => null,
                'security_scan_end_date' => null,
                'release_branch_creation_date' => null,
                'documentation_start_date' => null,
                'documentation_end_date' => null,
                'code_freeze_date' => null,
                'release_candidate_date' => '2020-02-19',
                'final_qa_date' => '2020-02-19',
                'release_build_date' => '2020-02-25',
                'has_pre_release' => 'N',
                'pre_release_1_date' => '2020-02-05',
                'has_pre_release_2' => 'N',
                'pre_release_2_date' => null,
                'has_pre_release_3' => 'N',
                'pre_release_3_date' => null,
                'has_pre_release_4' => 'N',
                'pre_release_4_date' => null,
                'milestone_notes' => null,
                'released_date' => '2020-02-26',
                'created_at' => '2020-04-28 18:46:13',
                'updated_at' => '2020-04-28 18:49:50',
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'release_numbers_id' => 4,
                'release_start_date' => '2020-02-26',
                'release_end_date' => '2020-05-19',
                'baseline_start_date' => null,
                'baseline_end_date' => null,
                'number_of_sprints' => null,
                'content_complete_start_date' => null,
                'content_complete_end_date' => '2020-05-11',
                'regressions_start_date' => null,
                'regressions_end_date' => null,
                'enablement_delivery' => 'Y',
                'enablement_delivery_start_date' => null,
                'enablement_delivery_end_date' => null,
                'localization_review' => 'Y',
                'localization_start_date' => null,
                'localization_end_date' => null,
                'run_security_scan' => 'Y',
                'security_scan_start_date' => null,
                'security_scan_end_date' => null,
                'release_branch_creation_date' => null,
                'documentation_start_date' => '2020-05-18',
                'documentation_end_date' => '2020-05-18',
                'code_freeze_date' => null,
                'release_candidate_date' => '2020-05-18',
                'final_qa_date' => '2020-05-18',
                'release_build_date' => '2020-05-19',
                'has_pre_release' => 'N',
                'pre_release_1_date' => '2020-03-23',
                'has_pre_release_2' => 'N',
                'pre_release_2_date' => '2020-04-15',
                'has_pre_release_3' => 'N',
                'pre_release_3_date' => '2020-05-11',
                'has_pre_release_4' => 'N',
                'pre_release_4_date' => null,
                'milestone_notes' => 'Pre-Release 1 and Pre-Release 2 were given to Boeing.
Pre-Release 2 given to Trane.',
                'released_date' => '2020-05-19',
                'created_at' => '2020-04-28 18:50:26',
                'updated_at' => '2020-06-25 14:14:31',
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'release_numbers_id' => 5,
                'release_start_date' => '2020-01-01',
                'release_end_date' => '2020-05-29',
                'baseline_start_date' => null,
                'baseline_end_date' => '2020-02-13',
                'number_of_sprints' => null,
                'content_complete_start_date' => '2020-04-24',
                'content_complete_end_date' => '2020-04-24',
                'regressions_start_date' => null,
                'regressions_end_date' => null,
                'enablement_delivery' => 'Y',
                'enablement_delivery_start_date' => null,
                'enablement_delivery_end_date' => null,
                'localization_review' => 'Y',
                'localization_start_date' => '2020-04-13',
                'localization_end_date' => '2020-05-08',
                'run_security_scan' => 'Y',
                'security_scan_start_date' => null,
                'security_scan_end_date' => '2020-05-08',
                'release_branch_creation_date' => '2020-05-12',
                'documentation_start_date' => '2020-05-11',
                'documentation_end_date' => '2020-05-21',
                'code_freeze_date' => '2020-05-12',
                'release_candidate_date' => null,
                'final_qa_date' => '2020-05-22',
                'release_build_date' => '2020-05-28',
                'has_pre_release' => 'N',
                'pre_release_1_date' => null,
                'has_pre_release_2' => 'N',
                'pre_release_2_date' => null,
                'has_pre_release_3' => 'N',
                'pre_release_3_date' => null,
                'has_pre_release_4' => 'N',
                'pre_release_4_date' => null,
                'milestone_notes' => null,
                'released_date' => '2020-06-01',
                'created_at' => '2020-04-28 18:50:57',
                'updated_at' => '2020-06-25 14:07:55',
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'release_numbers_id' => 6,
                'release_start_date' => '2020-01-15',
                'release_end_date' => '2020-05-29',
                'baseline_start_date' => null,
                'baseline_end_date' => null,
                'number_of_sprints' => null,
                'content_complete_start_date' => null,
                'content_complete_end_date' => '2020-05-12',
                'regressions_start_date' => null,
                'regressions_end_date' => null,
                'enablement_delivery' => 'Y',
                'enablement_delivery_start_date' => null,
                'enablement_delivery_end_date' => null,
                'localization_review' => 'Y',
                'localization_start_date' => null,
                'localization_end_date' => null,
                'run_security_scan' => 'Y',
                'security_scan_start_date' => null,
                'security_scan_end_date' => null,
                'release_branch_creation_date' => null,
                'documentation_start_date' => null,
                'documentation_end_date' => null,
                'code_freeze_date' => null,
                'release_candidate_date' => null,
                'final_qa_date' => null,
                'release_build_date' => null,
                'has_pre_release' => 'N',
                'pre_release_1_date' => null,
                'has_pre_release_2' => 'N',
                'pre_release_2_date' => null,
                'has_pre_release_3' => 'N',
                'pre_release_3_date' => null,
                'has_pre_release_4' => 'N',
                'pre_release_4_date' => null,
                'milestone_notes' => null,
                'released_date' => '2020-06-01',
                'created_at' => '2020-04-28 18:54:03',
                'updated_at' => '2020-06-25 14:06:31',
                'deleted_at' => null,
            ],
        ]);
    }
}
