<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProductVersionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_versions', function (Blueprint $table) {
            $table->increments('id');
            $table->string('product_ver_number');
            $table->integer('product_build_numer');
            $table->string('pv_id')->unique(); //generated by mergin above 2 fields added 12/Feb/2019
            $table->char('is_release_build', 1)->nullable()->default('N'); // field added on 8 april for Sizing
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_versions');
    }
}
